# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Записная книжка
tagline:          'Чтобы самому не забыть и другим рассказать'
description:      'Чтобы самому не забыть и другим рассказать'
paginate:         5
paginate_path:    "/portfolio/page:num/"
url:              https://erniess.github.io/
baseurl:          "/about_me"

author:
  name:           Alexey Tarara
  url:            erniess.github.io

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/Erniess
